export default
{
    "DashHeaderModule": {
        "lnkDashLogo": {findBy: "css", value: ".nav-logo"},
        "lnkDashHome": {findBy: "css", value: ".nav-dashboards"},
        "lnkDashNotification": {findBy: "xpath", value: "//*[@id='navbar']/ul/li[2]"},
        "lnkDashView": {findBy: "xpath", value: "//*[@id='navbar']/ul/li[3]"},
        "lnkDashFullScreen": {findBy: "xpath", value: "//*[@id='navbar']/ul/li[4]"},
        "lnkDashProfileIcon": {findBy: "xpath", value: "//*[@id='navbar']/ul/li[5]"},
    },
    "DashWebViewerModule": {
        "btnWevViewerAddIcon": {findBy: "css", value: "button[ng-click='addNewWebPage()']"},
        "txtFldWebViewerSiteUrl": {findBy: "model", value: "webPageInfo.url"},
        "btnWebViewerSiteTest": {findBy: "xpath", value: "//button [contains(text(),'Test')]"},
        "btnWebViewerSiteCancel": {findBy: "css", value: "button[ng-click='close()']"},
        "txtFldWebViewerSiteBookmark": {findBy: "model", value: "webPageInfo.description"},
        "btnWebViewerAddAsLink": {findBy: "css", value: "button[ng-click='addLink()']"},
        "btnWebViewerAddWbSiteAddress": {findBy: "css", value: "button[ng-click='addWebsiteAddress()']"},
        "lnkWebSitesUnderWebViewer": {findBy: "repeater", value: "webSite in webSites"},
        "lnkMediaSitesNavIconUnderWebViewer": {findBy: "xpath", value: "//a[@class='text-muted']/i"},
        "btnSaveWebViewerRecords": {findBy: "xpath", value: "//button [contains(text(),'Save (ctrl+s)')]"},
        "lblLinkURLTestToolTip": {findBy: "xpath", value: "//*[@ng-if='formState == formStates.popout']"},
        "lblWebURLTestToolTip": {findBy: "xpath", value: "//*[@ng-if='formState == formStates.works']"}
    },
    "DashFileShareModule": {
        "brnFileShareAgree": {findBy: "css", value: "button[ng-click='iAgree()']"},
        "brnFileShareUploadIcon": {findBy: "name", value: "files"},
        "btnSaveFileShareRecords": {findBy: "xpath", value: "//button [contains(text(),'Save (ctrl+s)')]"},
        "btnFileShareDownload": {findBy: "css", value: "a[uib-tooltip='Download']"},
        "btnFileShareDeleteFile": {findBy: "css", value: "span[ng-click='grid.appScope.openDeleteModal(row.entity)']"},
        "btnFileShareDeleteConfirm": {findBy: "css", value: "button[ng-click='delete()']"},
        "btnFileShareTableRecord": {findBy: "binding", value: "row.entity.UpdatedByUser"},
    },
    "DashNewsreelModule": {
        "btnNewsreelPaginationList": {findBy: "repeater", value: "slide in slides()"},
        "btnNewsreelAddIcon": {findBy: "css", value: "button[ng-click='showNewStoryModal()']"},
        "txtFldNewsreelHeadline": {findBy: "css", value: "input[name='title']"},
        "txtFldNewsreelSummary": {findBy: "model", value: "story.summary"},
        "btnNewsreelBrowseEditClose": {findBy: "xpath", value: "//button [contains(text(),'Close')]"},
        "ddlDivisionOption": {findBy: "xpath", value: "//select [@ng-change='changeDivision(selDivision)']"},
        "ddlOrganizationOption": {findBy: "xpath", value: "//select [@ng-model='selOrg']"},
        "ddlTeamOption": {findBy: "model", value: "selTeam"},
        "btnNewsreelAddScope": {findBy: "css", value: "button[data-ng-click='addScope()']"},
        "btnNewsreelAddStory": {findBy: "css", value: "button[ng-click='saveStory()']"},
        "btnSaveWebViewerRecords": {findBy: "xpath", value: "//button [contains(text(),'Save (ctrl+s)')]"},
        "btnNewsreelRecordsEdit": {findBy: "xpath", value: "//*[@id='app']//widget/div[1]/div[2]/div/div/div[2]/div[4]/div[2]/div/div[1]/button"},
        "btnNewsreelRecordsDelete": {findBy: "xpath", value: "//*[@id='app']//widget/div[1]/div[2]/div/div/div[1]/div[4]/div[2]/div/div[2]/button"},
        "btnNewsreelRecordsDeleteConfirm": {findBy: "css", value: ".submit-modal"},
        "btnNewsreelPaginations": {findBy: "css", value: "li[ng-click='select(slide)']"},
    },
}