export enum Locators{
    Id = <any> "id",
    Css = <any> "css",
    Model = <any> "model",
    Binding = <any> "binding",
    ButtonText = <any> "buttonText",
    PartialButtonText = <any> "partialButtonText",
    LinkText = <any> "linkText",
    PartialLinkText = <any> "partialLinkText",
    CssContainingText = <any> "cssContainingText",
    ExactBinding = <any> "exactBinding",
    Repeater = <any> "repeater",
    ExactRepeater = <any> "exactRepeater",
    Options = <any> "options",
    DeepCss = <any> "deepCss",
    ClassName = <any> "className",
    Name = <any> "name",
    TagName = <any> "tagName",
    Xpath = <any> "xpath",
}
